name: release

on:
  # trigger deployment on every push to main branch
  push:
    branches: main
  # trigger deployment manually
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: shaders
          path: dist/dl

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H%M')"

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: tag-${{ steps.date.outputs.date }}
          name: shaders-${{ steps.date.outputs.date }}
          gzip: folders
          files: shaders:dl/