name: release

on:
  # trigger deployment on every push to main branch
  push:
    branches: main
  # trigger deployment manually
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # choose node.js version to use
          node-version: '16'

      # run build script
      - name: Output shaders
        run: node release.js

      - name: Zip shaders
        run: zip -q -r -9 "shaders.zip" shaderCache

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H%M')"

      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: tag-${{ steps.date.outputs.date }}
          name: shaders-${{ steps.date.outputs.date }}
          gzip: false
          files: shaders.zip